🧪  Layer squashing, a uniqueness `BONRefiner`, some early network vignette functions
EcoJulia/BiodiversityObservationNetworks.jl pull request #16
Opened 2022-08-24 15:43 UTC by gottacatchenall

Main things in this PR:

- A new `BONRefiner` that picks the N-most unique locations from a seeded set of coordinates across a set of layers passed to it
- Optimization of environmental uniqueness as a vignette (in `./docs/vignettes/uniqueness.jl`)
- The `squash` function, for taking a weight matrix and vector and collapses many layers into one.
- Lazy-loading of the SimpleSDMLayers, NeutralLandscapes, and Zygote packages. 
    - SimpleSDMs: Integration with `missing` values in maps
    - Zygote: Implementation of AD gradient descent  
- Simulation of metaweb sampling functions for the forthcoming network vignette (in `./docs/vignettes/networks.jl`)

2022-08-25 14:05 UTC, gottacatchenall commented
Should we merge this and implement batching in a new PR? @tpoisot

2022-08-25 14:57 UTC, tpoisot commented
Yeah

2022-08-25 15:00 UTC, tpoisot requested changes

2022-08-25 15:00 UTC, tpoisot commented on misc/metaweb_generation.jl
> +# ===============================================
shouldn't this be a vignette?

2022-08-25 15:00 UTC, tpoisot commented on src/optimize.jl
> +"""
docstring isn't updated

2022-08-25 15:00 UTC, tpoisot commented on src/optimize.jl
> +struct Weights{F <: AbstractFloat}
is it actually used?

2022-08-25 15:00 UTC, tpoisot commented on src/optimize.jl
> +using Statistics, StatsBase
drop this from the file

2022-08-25 15:00 UTC, tpoisot commented on src/optimize.jl
> +dims, nl, nt = (50, 50), 5, 3
drop this from the file (move to tests?)

2022-08-31 16:15 UTC, gottacatchenall commented
I'm planning to add a new `BONRefiner` called `Uniqueness` that selects the `n`-sites with the least mean covariance with other sites, e.g. if total covar per site is calculated as $C_i  = \sum_j \text{Cov}(i,j)$, this `Refiner` takes `N` points and returns the `m` points with the smallest values of $C\_i$.

This creates an issue in how the api would work, because we want to pass `Uniqueness` a set of environmental layers (An Array{T,3}, instead of a Matrix), e.g.

```
candidates = zeros(50,50) |> seed(AdaptiveSampling())
refine(candidates, Uniqueness(), layers)
```

Two solution I can see for this are

(1) dropping the type restriction on `uncertainty` as an matrix and doing an argument check inside `_generate`

or 

(2) store layers as a field in `Uniqueness` and ignore the `uncertainty` matrix passed to it by `refine`

@tpoisot

2022-08-31 18:06 UTC, gottacatchenall commented
i went with (2)

2022-09-10 19:58 UTC, gottacatchenall commented
seems ready for review @tpoisot

2022-09-11 14:06 UTC, tpoisot approved these changes

2022-09-11 14:07 UTC, tpoisot commented
Do you want to tag when merged?

2022-09-11 14:16 UTC, merged

2022-09-11 15:25 UTC, gottacatchenall commented
yeah sure